data_ingestion:
  method: kagglehub
  available_methods:
    kagglehub:
      source: ronakbadhe/chess-evaluations
      install_path: dataset/raw/

data_preprocessing:
  input_path: dataset/raw/
  output_path: dataset/preprocessed/
  output_file: preprocessed.csv
  max_mate_value: 30000
  min_mate_value: 1000
  scaling_factor: 500


data_transformation:
  output_path: dataset/transformed/
  input_file: dataset/preprocessed/preprocessed.csv
  val_split: 0.05

dataset_entity:
  input_path: dataset/transformed/
  batch_size: 32
  shuffle: True
  num_workers: 1

models:
  current_model: resnet_3M_se
  available_models:

    resnet_3M_se:
      model_type: resnet
      params:
        num_blocks: 10
        num_filters: 128
        value_head_hidden: 128
        use_se: True
    
    resnet_18M_se:
      model_type: resnet
      params:
        num_blocks: 15
        num_filters: 256
        value_head_hidden: 256
        use_se: True
    
    resnet_24M_se:
      model_type: resnet
      params:
        num_blocks: 20
        num_filters: 256
        value_head_hidden: 256
        use_se: True
    
    resnet_54M_se:
      model_type: resnet
      params:
        num_blocks: 20
        num_filters: 384
        value_head_hidden: 256
        use_se: True
    
    resnet_143M_se:
      model_type: resnet
      params:
        num_blocks: 30
        num_filters: 512
        value_head_hidden: 512
        use_se: True

model_trainer:
  learning_rate: 0.005
  weight_decay: 1.0e-4
  checkpoint_dir: checkpoints/
  num_epochs: 50
  early_stopping_patience: 10